apiVersion: v1
kind: ConfigMap
metadata:
  name: httpbin-service-config
  namespace: default
data:
  AUDIT_DB_HOST: {{ .Values.config.audit_db_host | quote }}
  AUDIT_DB_PORT: {{ .Values.config.audit_db_port | quote }}
  AUDIT_DB_NAME: {{ .Values.config.audit_db_name | quote }}
  AUDIT_RETENTION_DAYS: {{ .Values.config.audit_retention_days | quote }}
