apiVersion: v1
kind: ConfigMap
metadata:
  name: httpbin-config
  namespace: default
  labels:
    app: httpbin
data:
  AUDIT_DB_HOST: {{ .Values.httpbin.db.host | quote }}
  AUDIT_DB_PORT: {{ .Values.httpbin.db.port | quote }}
  AUDIT_DB_NAME: {{ .Values.httpbin.db.name | quote }}
  AUDIT_RETENTION_DAYS: {{ .Values.httpbin.db.retentionDays | quote }}