apiVersion: v1
kind: Secret
metadata:
  name: httpbin-secret
type: Opaque
stringData:
  AUDIT_DB_HOST: {{ .Values.httpbin.db.host | quote }}
  AUDIT_DB_USER: {{ .Values.httpbin.db.user | quote }}
  AUDIT_DB_PASSWORD: {{ .Values.httpbin.db.password | quote }}