apiVersion: v1
kind: Secret
metadata:
  name: httpbin-secret
  namespace: default
  labels:
    app: httpbin
type: Opaque
stringData:
  AUDIT_DB_USER: {{ .Values.httpbin.db.user | quote }}
  AUDIT_DB_PASSWORD: {{ .Values.httpbin.db.password | quote }}