apiVersion: v1
kind: Secret
metadata:
  name: httpbin-service-secret
  namespace: default
type: Opaque
stringData:
  AUDIT_DB_USER: {{ .Values.secrets.audit_db_user | quote }}
  AUDIT_DB_PASSWORD: {{ .Values.secrets.audit_db_password | quote }}
