apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  namespace: default
  labels:
    app: httpbin-service
spec:
  type: ClusterIP
  selector:
    app: httpbin-service
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
