image: <+artifacts.primary.image>

config:
  audit_db_host: <+variable.audit_db_host>
  audit_db_port: "3306"
  audit_db_name: "httpbin_audit"
  audit_retention_days: "30"

secrets:
  audit_db_user: <+secrets.getValue("audit_db_user")>
  audit_db_password: <+secrets.getValue("audit_db_password")>
